PhoneStoreWeb/PhoneStoreWeb/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhoneStoreWeb.Areas.Admin.Model;
using PhoneStoreWeb.Models;
using PagedList;

namespace PhoneStoreWeb.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {

        PhoneStoreEntities1 db = new PhoneStoreEntities1();
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login (LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new User_DAO();
                var result=dao.Login(model.email,PhoneStoreWeb.Models.Common.Encryption.GetHashMD5(model.password));
                if (result == 1)
                {
                    var user = dao.getItem(model.email);
                    UserLogin session = new UserLogin();
                    session.Email = user.email;
                    session.UserId = user.id;
                    session.LastName = user.lastName;
                    session.FirstName = user.firstName;
                    session.Image=user.image;
                    Session["USER_SESSION"]=session;
                    return RedirectToAction("Index", "Home");

                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản chưa được kích hoạt");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Mật khẩu chưa chính xác");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại");
                }
            }
            return View("Index");
        }
        public ActionResult ListUser(int? page)
        {
            IEnumerable<tb_User> items = db.tb_User.OrderByDescending(x => x.id);
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
            
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add(tb_User model, string confirmPassword)
        {
            
            if (ModelState.IsValid)
            {
                String email = model.email;
                var dao = new User_DAO();
                List<tb_User> users = dao.getList();
                foreach (tb_User user in users)
                {
                    if(user.email == email)
                    {
                        ModelState.AddModelError("", "Tài khoản da tồn tại");
                        return View("Add");
                    }
                    else
                    {
                        if(model.password==confirmPassword)
                        {
                            if (model.password.Length < 6)
                            {
                                ModelState.AddModelError("", "Mật khẩu ít nhất 6 ký tự");
                                return View("Add");
                            }
                            else
                            {
                                model.password = PhoneStoreWeb.Models.Common.Encryption.GetHashMD5(model.password);
                                var status = Request.Form.GetValues("status")[0];
                                if (status == "true")
                                {
                                    model.status = true;
                                }
                                else
                                {
                                    model.status = false;
                                }
                                db.tb_User.Add(model);
                                db.SaveChanges();
                                return RedirectToAction("ListUser");
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("", "Vui lòng nhập lại mật khẩu");
                            return View("Add");
                        }
                       
                    }
                }
               


            }
           
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.tb_User.Find(id);
            if (item != null)
            {
               
                db.tb_User.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }
        [HttpPost]
        public ActionResult deleteAll(String ids)
        {
            List<String> listIdString = ids.Split(',').ToList();
            List<int> listId = listIdString.Select(int.Parse).ToList();
            foreach (int id in listId)
            {
                var item = db.tb_User.Find(id);
                if (item != null)
                {
                    db.tb_User.Remove(item);
                    db.SaveChanges();
                }
            }
            return Json(new { success = true });
        }
        public ActionResult IsActive(int id)
        {
            var item = db.tb_User.Find(id);
            Boolean status = item.status.Value;
            if (item != null)
            {
                db.tb_User.Attach(item);
                if (status == true)
                {
                    item.status = false;
                }
                else
                {
                    item.status = true;

                }

                db.Entry(item).Property(x => x.status).IsModified = true;
                db.SaveChanges();
                return Json(new { message = "Success", Success = true , isAcive = true });
            }
             return Json(new { success = false });

        }
    }
}

PhoneStoreWeb/PhoneStoreWeb/Controllers/NewsController.cs
using PhoneStoreWeb.Models;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace PhoneStoreWeb.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        PhoneStoreEntities1 db = new PhoneStoreEntities1();

        public ActionResult Index()
        {
            //var pageSize = 1;
            //if (page == null)
            //{
            //    page = 1;
            //}
            //IEnumerable<News> items = db.News.OrderByDescending(x => x.CreatedDate);
            //var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            //items = items.ToPagedList(pageIndex, pageSize);
            //ViewBag.PageSize = pageSize;
            //ViewBag.Page = page;
            var items = db.tb_News.ToList();
            return View(items);
        }

        public ActionResult Detail(int id)
        {
            var item = db.tb_News.Find(id);
            return View(item);
        }

        public ActionResult getNewsbyId(int id)
        {
            var v = from t in db.tb_News
                    where t.id == id
                    select t;
            return View(v.FirstOrDefault());
        }
    }
}

PhoneStoreWeb/PhoneStoreWeb/Areas/Admin/Views/Login/Add.cshtml
@model PhoneStoreWeb.Models.tb_User
@{
    ViewBag.Title = "Thêm người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/products" class="nav-link">Người dùng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới người dùng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Người dùng </a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin thêm mới </h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    @using (Html.BeginForm("Add", "Login", FormMethod.Post, new { }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        <div class="card">
                            <div class="card-header p-2">
                                <ul class="nav nav-pills">
                                    <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Thông tin chung</a></li>
                                   
                                </ul>
                            </div><!-- /.card-header -->
                            <div class="card-body">
                                <div class="tab-content">
                                    <div class="active tab-pane" id="activity">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Tên </label>
                                            @Html.TextBoxFor(x => x.firstName, new { @class = "form-control", @placeholder = "Vui lòng nhập tên" })
                                            @Html.ValidationMessageFor(x => x.firstName, null, new { @class = "text-danger" })
                                        </div>
                                        @*<div class="form-group">
            <label for="exampleInputEmail1">Meta</label>
            @Html.TextBoxFor(x => x.Meta, new { @class = "form-control", @placeholder = "Meta" })
            @Html.ValidationMessageFor(x => x.Meta, null, new { @class = "text-danger" })
        </div>*@

                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Họ</label>
                                            @Html.TextBoxFor(x => x.lastName, new { @class = "form-control", @placeholder = "Vui lòng nhập họ" })
                                            @Html.ValidationMessageFor(x => x.lastName, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Email</label>
                                            @Html.TextBoxFor(x => x.email, new { @class = "form-control", @placeholder = "Vui lòng nhập email" })
                                            @Html.ValidationMessageFor(x => x.email, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Mật khẩu</label>
                                            @Html.PasswordFor(x => x.password, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(x => x.password, null, new { @class = "text-danger", @placeholder = "Vui lòng nhập mật khẩu" } )
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Xác nhận mật khẩu</label>
                                            @Html.Password("confirmPassword","", new {@class = "form-control" ,  placeholder = "Vui lòng nhập lại mật khẩu" })
                                            @Html.ValidationMessageFor(x => x.password, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputFile">Ảnh đại hiện</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    @Html.TextBoxFor(x => x.image, new { @id = "txtImage", @class = "form-control" })
                                                </div>
                                                <div class="input-group-append">
                                                    <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage');" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-3">
                                                <div class="form-group">
                                                    <div class="custom-control custom-checkbox">
                                                        @Html.CheckBox("status", false)
                                                        <label>Status </label>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                   
                                    <!-- /.tab-pane -->
                                </div>
                                <!-- /.tab-content -->
                            </div><!-- /.card-body -->
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Thêm mới</button>
                            </div>
                        </div> <!-- /.card -->
                    }
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

@section  scripts{
    <script>
        $(document).ready(function () {
            $('.auto').autoNumeric('init');
            $('#demoPrice').bind('blur focusout keypress keyup', function () {
                var demoGet = $('#demoPrice').autoNumeric('get');
                $('#Price').val(demoGet);
                $('#Price').autoNumeric('set', demoGet);
            });
            $('#demoPriceSale').bind('blur focusout keypress keyup', function () {
                var demoGet = $('#demoPriceSale').autoNumeric('get');
                $('#PriceSale').val(demoGet);
                $('#PriceSale').autoNumeric('set', demoGet);
            });
            $('#demoOriginalPrice').bind('blur focusout keypress keyup', function () {
                var demoGet = $('#demoOriginalPrice').autoNumeric('get');
                $('#OriginalPrice').val(demoGet);
                $('#OriginalPrice').autoNumeric('set', demoGet);
            });
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });

            $('body').on('click', '.btnXoaAnh', function () {
                var conf = confirm('Bạn có muốn xóa ảnh này không?');
                if (conf === true) {
                    var _id = $(this).data('id');
                    $('#trow_' + _id).fadeTo('fast', 0.5, function () {
                        $(this).slideUp('fast', function () { $(this).remove(); });
                    });
                    var temp = $('#tCurrentId').val();
                    var currentId = parseInt(temp) - 1;
                    $('#tCurrentId').val(currentId);
                }
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
        function addImageProduct(url) {
            var temp = $('#tCurrentId').val();
            var currentId = parseInt(temp) + 1;
            var str = "";
            if (currentId == 1) {
                str += `<tr id="trow_${currentId}">
                                <td class="text-center">${currentId}</td>
                                <td class="text-center"><img width="80" src="${url}" /> <input type='hidden' value="${url}" name="Images"/></td>
                                <td class="text-center"><input type="radio" name="rDefault" value="${currentId}" checked="checked"/></td>
                                <td class="text-center"><a href="#" data-id="${currentId}" class="btn btn-sm btn-danger btnXoaAnh">Xóa</a></td>
                                </tr>`;
            }
            else {
                str += `<tr id="trow_${currentId}">
                                <td class="text-center">${currentId}</td>
                                <td class="text-center"><img width="80" src="${url}" /> <input type='hidden' value="${url}" name="Images"/></td>
                                <td class="text-center"><input type="radio" name="rDefault" value="${currentId}"/></td>
                                <td class="text-center"><a href="#" data-id="${currentId}" class="btn btn-sm btn-danger btnXoaAnh">Xóa</a></td>
                                </tr>`;
            }
            $('#tbHtml').append(str);
            $('#tCurrentId').val(currentId);
            //$('#tbHtml tr td a').each(function () {
            //    $(this).click(function () {
            //        var conf = confirm('Bạn có muốn xóa ảnh này không?');
            //        if (conf === true) {
            //            var _id = $(this).data('id');
            //            $('#trow_' + _id).fadeTo('fast', 0.5, function () {
            //                $(this).slideUp('fast', function () { $(this).remove(); });
            //            });
            //            var temp = $('#tCurrentId').val();
            //            var currentId = parseInt(temp) - 1;
            //            $('#tCurrentId').val(currentId);
            //        }
            //    });
            //});
        }
    </script>
}

PhoneStoreWeb/PhoneStoreWeb/Areas/Admin/Views/Login/Index.cshtml
@model PhoneStoreWeb.Areas.Admin.Model.LoginModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutLogin.cshtml";
}

<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                @using (Html.BeginForm("Login", "Login", FormMethod.Post))
                {
                    @Html.ValidationSummary(false, "", new {@class="text-danger"})
                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <label class="form-label" for="form3Example3">Email address</label>
                       @Html.TextBoxFor(x => x.email, new {@class="form-control form-control-lg", @placeholder="Enter a valid email address" })
                    </div>

                    <!-- Password input -->
            <div class="form-outline mb-3">
                <label class="form-label" for="form3Example4">Password</label>
                @Html.PasswordFor(x => x.password, new { @class = "form-control form-control-lg", @placeholder = "Enter a valid password" })

            </div>

                    <div class="d-flex justify-content-between align-items-center">
                        <!-- Checkbox -->
                        <div class="form-check mb-0">
                            @Html.CheckBoxFor(x => x.remember)
                            <label class="form-check-label" for="form2Example3">
                                Remember me
                            </label>
                        </div>

                    </div>

                    <div class="text-center text-lg-start mt-4 pt-2">
                        <button type="submit" class="btn btn-primary btn-lg"
                                style="padding-left: 2.5rem; padding-right: 2.5rem;">
                            Login
                        </button>

                    </div>

                }

            </div>
        </div>
    </div>
    
</section>

PhoneStoreWeb/PhoneStoreWeb/Areas/Admin/Views/Login/ListUser.cshtml
@model PagedList.PagedList<PhoneStoreWeb.Models.tb_User>
@using PagedList.Mvc
@{
    ViewBag.Title = "Danh sách người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/category" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.Title</h3>

            <div class="card-tools">
                <a href="/admin/login/add" class="btn btn-primary">Thêm mới</a>
                <a href="#" class="btn btn-danger" id="BtnDeleteAll">Xóa</a>
            </div>
        </div>
        <div class="card-body">
            @*<div class="row">
                    <div class="col-6">
                        @using (Html.BeginForm("index", "News", FormMethod.Get, new { }))
                        {
                            <div class="input-group input-group-sm">
                                @Html.TextBox("Searchtext", new { @class = "form-control" })
                                <span class="input-group-append">
                                    <button type="submit" class="btn btn-info btn-flat">Tìm kiếm</button>
                                </span>
                            </div>
                        }
                    </div>
                </div>*@
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="SelectAll" /></th>
                        <th>STT</th>
                        <th>Hình ảnh</th>
                        <th>Họ</th>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Trạng Thái</th>
                        
                        <th style="width:150px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.Page - 1) * ViewBag.PageSize) + 1;
                        foreach (var item in Model)
                        {
                            var strCheck = item.status.Value ? "<i class='fa fa-check text-success'></i>" : "<i class='fas fa-times text-danger'></i>";
                            //var strCheckHome = item.IsHome ? "<i class='fa fa-check text-success'></i>" : "<i class='fas fa-times text-danger'></i>";
                           
                            var strImg = "";
                            var CheckImage = item.image;
                            if (CheckImage != null)
                            {
                                strImg = CheckImage;
                            }
                            <tr id="trow_@item.id">
                                <td><input type="checkbox" class="cbkItem" value="@item.id" /></td>
                                <td>@i</td>
                                <td><img class="imgproduct" data-id="@item.id" src="@strImg" width="50" /></td>
                                <td>@item.firstName</td>
                                <td>@item.lastName</td>
                                <td>@item.email</td>
                               
                                
                                <td class="text-center">
                                    <a href='#' data-id="@item.id" class="btnActive">@Html.Raw(strCheck)</a>
                                </td>
                                <td>
                                   
                                    <a href="#" data-id="@item.id" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi nào!!!</td>
                        </tr>
                    }
                </tbody>
            </table>

            <div class="row">
                <div class="col-6"></div>
                <div class="col-6" style="text-align:right;">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
<div id="dialog">
    <iframe id="myIframe" style="border: 0; width: 100%; height: 100%;"></iframe>
</div>
@section scripts{
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            //hiển thị form upload ảnh
            
            $('body').on('click', '#BtnDeleteAll', function (e) {
                e.preventDefault();
                var str = "";
                var checkbox = $(this).parents('.card').find('tr td input:checkbox');
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
                if (str.length > 0) {
                    var conf = confirm('Bạn có muốn xóa các bản ghi này hay không?'+str);
                    if (conf === true) {
                        $.ajax({
                            url: '/admin/login/deleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });

            $('body').on('change', '#SelectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
            });
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không?');
                if (conf === true) {
                    $.ajax({
                        url: '/admin/login/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
            
            $('body').on('click', '.btnActive', function (e) {
                e.preventDefault();
                var btn = $(this);
                var id = btn.data("id");
                var conf = confirm('Bạn có muốn cập nhật trạng thái tài khoản không ?');
                if (conf === true) {
                    $.ajax({
                        url: '/admin/login/IsActive',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                if (rs.isAcive) {
                                    btn.html("<i class='fa fa-check text-success'></i>");
                                    //$(this).find("i").removeClass("fas fa-times text-danger")
                                    //$(this).find("i").addClass("fa fa-check text-success");

                                   
                                } else {
                                    btn.html("<i class='fas fa-times text-danger'></i>");
                                    
                                }
                            }

                        }
                    });
                    location.reload();
                }
                
            });
        });
    </script>
}